import Link from "next/link";
import { desc, eq } from "drizzle-orm";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/db";
import { entries, paths } from "@/db/schema";
import { calculateStats } from "@/lib/stats";
import { SiteHeader } from "@/components/site-header";

export default async function Dashboard() {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  const allPaths = await db.select().from(paths).where(eq(paths.userId, user.id)).orderBy(desc(paths.updatedAt));
  const allEntries = await db.select().from(entries).where(eq(entries.userId, user.id)).orderBy(desc(entries.date));
  const recent = allEntries.slice(0, 8);
  const stats = calculateStats(allEntries.map((entry) => entry.date));
  return <><SiteHeader /><main className="mx-auto w-full max-w-6xl px-5 py-10"><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Your learning workspace</p><h1 className="mt-1 text-3xl font-bold">Good to see you, {user.name.split(" ")[0]}.</h1></div><Link href="/dashboard/paths/new" className="rounded-lg bg-foreground px-4 py-2.5 text-sm font-medium text-background">New path</Link></div><div className="mb-10 grid gap-4 sm:grid-cols-3"><Stat label="Active paths" value={allPaths.length} /><Stat label="Current streak" value={`${stats.current} day${stats.current === 1 ? "" : "s"}`} /><Stat label="Longest streak" value={`${stats.longest} day${stats.longest === 1 ? "" : "s"}`} /></div><div className="mb-10 rounded-xl border p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Activity</h2><span className="text-xs text-muted-foreground">Last 10 weeks</span></div><div className="grid grid-cols-10 gap-1.5">{heatmap(stats.dates).map((cell) => <span key={cell.date} title={`${cell.date}: ${cell.count} entr${cell.count === 1 ? "y" : "ies"}`} className={`aspect-square rounded-sm ${cell.count ? "bg-foreground" : "bg-muted"}`} />)}</div></div><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><section><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Your paths</h2><span className="text-sm text-muted-foreground">{allPaths.length} total</span></div>{allPaths.length ? <div className="grid gap-3">{allPaths.map((path) => <Link key={path.id} href={`/dashboard/paths/${path.id}`} className="rounded-xl border p-5 transition hover:-translate-y-0.5 hover:shadow-sm"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{path.title}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{path.description || "No description yet."}</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs">{path.isPublic ? "Public" : "Private"}</span></div><p className="mt-4 text-xs text-muted-foreground">/{path.slug}</p></Link>)}</div> : <div className="rounded-xl border border-dashed p-10 text-center"><p className="font-medium">Your first path starts here.</p><p className="mt-1 text-sm text-muted-foreground">Create a small, specific learning goal.</p><Link href="/dashboard/paths/new" className="mt-5 inline-block text-sm underline">Create a path</Link></div>}</section><section><h2 className="mb-4 text-lg font-semibold">Recent activity</h2><div className="rounded-xl border">{recent.length ? recent.map((entry) => <div key={entry.id} className="border-b p-4 last:border-0"><p className="text-xs text-muted-foreground">{entry.date}</p><p className="mt-1 text-sm">{entry.content}</p></div>) : <p className="p-6 text-sm text-muted-foreground">Your completed days will appear here.</p>}</div></section></div></main></>;
}
function heatmap(dates: string[]) { const counts = new Map<string, number>(); dates.forEach((date) => counts.set(date, (counts.get(date) ?? 0) + 1)); const end = new Date(); end.setUTCHours(0, 0, 0, 0); const start = new Date(end.getTime() - 69 * 86400000); return Array.from({ length: 70 }, (_, index) => { const date = new Date(start.getTime() + index * 86400000).toISOString().slice(0, 10); return { date, count: counts.get(date) ?? 0 }; }); }
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
